spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebankify
    username: postgres
    password: latifa
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      format-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
keycloak:
  realm: BankApp
  auth-server-url: http://localhost:8081
  resource: bank-client
  public-client: false
  credentials:
    secret: "s4bRYEyhPS7aiYa0kodshJfBze5fxfSk"
  bearer-only: true
  ssl-required: external
  admin:
    username: admin
    password: admin
    client-id: bank-app-client
    realm: BankApp
  policy-enforcer-config:
    enforcement-mode: ENFORCING